server :
    port:  8080
    host: 127.0.3.1 # 0 on the end handled
    server_name : mmoumani.42.fr1
    root: www
    # client_max_body_size: 10M
    upload : on upload 
    autoindex : on
    methods: POST GET
    # index : index.html index.htmld
    # index : home.html index.htmld2 # is dir
    time_out : 5s
    error_pages : [[404 500 502 503 504, error_pages/custom_40x.html]]

    location :   
        - path : /home
        - autoindex : ON    
        - upload : on
        - index : index.html
        - cgi_paths : [[.py , /usr/bin/python3], [.php, /usr/bin/php-cgi]]
        - error_pages : [[404, error_pages/custom_40x.html]]  
    location :
        - path:  /
        # - methods:  POST
        # - return : 301  http://google.com

server : 
    server_name     : mmoumani
    host: 127.0.3.1

    port: 8080
    root: www
    index : congradulation 

server : 
    server_name : mmoumani.42.fr3
    host: 127.0.3.1

    port: 8082
    root: www
