server :
    port:  8080
    host: 127.0.3.1 # 0 on the end handled
    server_name : mmoumani.42.fr1
    root: www
    client_max_body_size: 10M
    upload : on upload 
    autoindex : OFF
    methods: POST GET
    index : index.html index.htmld
    index : home.html index.htmld2
    time_out : 1m
    error_pages : [[400 500 502 503 504, error_pages/custom_50x.html]]
    location :   
        - path : /home
        - autoindex : ON    
        - upload : on
        - index : home.html
        - error_pages : [[400, error_pages/custom_40x.html]]  
        - return : 301   sdfs   dfsf

    location :
        - path:  /home/user/index.html 
        - index : home.html
        - methods:  POST

server : 
    server_name     : mmoumani
    host: 127.0.3.1

    port: 8080
    root: www
    index : congradulation 

server : 
    server_name : mmoumani.42.fr3
    host: 127.0.3.1

    port: 8082
    root: www
