server :
    port:  8080
    host: 127.0.3.1
    server_name : mmoumani.42.fr1
    root: www
    client_max_body_size: 20M
    upload : on upload #
    autoindex : ON
    methods: POST GET
    index : index.html index.htmld
    index : home.html index.htmld2
    error_pages : [[400 500 502 503 504, error_pages/custom_50x.html], [400 400 402 403 404, custom_40x.html]]   
    location :   
        - path : /home
        - autoindex : ON     
        - upload : on  
        - error_pages : [[400, error_pages/custom_40x.html]]  
        - retrun : 301   sdfs   dfsf

    location :
        - path:  /home/user/index.html 
        - index : home1.html
        - index : home.html
        - methods:  POST

server : 
    server_name     : mmoumani
    host: 127.0.3.1

    port: 8080
    root: www
    index : congradulation 

server : 
    server_name : mmoumani.42.fr3
    host: 127.0.3.1

    port: 8082
    root: www
