server :
    # doublicate 
    port:  8080
    host: 127.0.3.1
    server_name : mmoumani.42.fr1
    root: www
    client_max_body_size: 20M
    upload : on  upload/
    autoindex : ON
    methods: POST GET
    index : index.html index.htmld
    index : home.html index.htmld2
    error_pages : [[400 500 502 503 504, error_pages/custom_50x.html], [400 400 402 403 404, custom_40x.html]]   
    root: upload
    location :   
        - path : /home
        - autoindex : ON     
        - upload : off  
        - error_pages : [[400, error_pages/custom_40x.html]]  
        - retrun : 301   sdfs   dfsf

    location :
        - path:  /home/user/index.html 
        - index : home1.html
        - index : home.html
        # - cgi_path : [.py, /usr/bin/python3]
        # - cgi_path : [.php, /usr/bin/php-cgi]
        # cgi_path : extantion(python | php ...) /path 
        - methods:  POST
    # location :   
    #     path:  hsf3 
    #     # cgi_path : extantion(python | php ...) /path 
    #     methods: post / get / delete
    # location :  
    #     path:  hsf4 # sdf
    #     # cgi_path : extantion(python | php ...) /path 
    #     # methods: post / get / delete

server : 
    # change if two servers have the same server_name
    server_name     : mmoumani
    host: 127.0.3.1

    port: 8080
    root: www
    index : congradulation 


    # location :
    #     - path:  \.php$2
    #     - methods: DELETE
        
    # location :  
    #     - path:  \.php$2
    #     - methods: DELETE


server : 
    server_name : mmoumani.42.fr3
    host: 127.0.3.1

    port: 8082
    root: www
